In [ ]:
# Data Sources http://web.mta.info/developers/turnstile.html

In [ ]:
startdate = datetime.datetime.strptime('2018-12-29', '%Y-%m-%d').date()
enddate = datetime.datetime.strptime('2021-01-31', '%Y-%m-%d').date()
print(startdate, enddate)

In [ ]:
from dateutil.relativedelta import relativedelta

In [ ]:
dataset = pd.DataFrame()
while startdate<=enddate:
    file_name = 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_'+ startdate.strftime('%y%m%d') +'.txt'
    print(file_name)
    tdata = pd.read_csv(file_name)
    tdata.columns = ['CA', 'UNIT', 'SCP', 'STATION', 'LINENAME', 'DIVISION', 'DATE', 'TIME', 'DESC', 'ENTRIES', 'EXITS']
    tdata['file_name'] = startdate
    tdata.to_csv(str(startdate)+'_data.csv', sep = '|', index = False)
    startdate = startdate+relativedelta(days = 7)

In [1]:
import glob
import pandas as pd
import os

data = pd.DataFrame()
print(data.shape)

for i in glob.glob(os.getcwd()+"/*.csv"):
    print(i)
    get_data = pd.read_csv(i, sep = '|')
    data = data.append(get_data)

print(data.shape)

(0, 0)
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2018-12-29_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-01-05_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-01-12_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-01-19_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-01-26_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-02-02_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-02-09_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-02-16_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-02-23_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-03-02_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-03-09_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-03-16_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-03-23_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-03-30_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-04-06_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-04-13_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-04-20_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-04-27_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-05-04_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-05-11_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-05-18_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-05-25_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-06-01_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-06-08_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-06-15_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-06-22_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-06-29_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-07-06_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-07-13_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-07-20_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-07-27_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-08-03_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-08-10_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-08-17_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-08-24_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-08-31_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-09-07_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-09-14_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-09-21_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-09-28_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-10-05_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-10-12_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-10-19_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-10-26_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-11-02_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-11-09_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-11-16_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-11-23_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-11-30_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-12-07_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-12-14_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-12-21_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2019-12-28_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2020-01-04_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2020-01-11_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2020-01-18_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2020-01-25_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2020-02-01_data.csv
C:\Users\Anant Awasthi\Desktop\Desktop\NYC\2020-02-08_data.csv
(12107424, 12)

In [2]:
data.to_csv('Combind_data.csv', index=False, sep='|')

In [3]:
data.head()

,CA,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,file_name
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/22/2018,03:00:00,REGULAR,6881995,2333630,2018-12-29
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/22/2018,07:00:00,REGULAR,6882006,2333643,2018-12-29
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/22/2018,11:00:00,REGULAR,6882062,2333740,2018-12-29
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/22/2018,15:00:00,REGULAR,6882243,2333800,2018-12-29
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/22/2018,19:00:00,REGULAR,6882590,2333868,2018-12-29